### ISSUE TITLE
Google Play Services

### ISSUE THREAD

**Issue by jbro129** [FBlackBox/BlackBox#10]
Does BlackBox support running Google Play Services within the environment?
Like how VA has https://github.com/asLody/VirtualApp/blob/master/VirtualApp/lib/src/main/java/com/lody/virtual/GmsSupport.java#L24 and how the services supposedly work in the 'commercial version'

**Comment by crazyn2** [comment]
In the future, it doesn't support GMS now.

**Comment by FBlackBox** [comment]
See https://github.com/FBlackBox/BlackBox/commit/3cdf3c79036291696c060c43551ae866478246cd

Simple version, there are still many problems (only when using GMS).Because the AccountManager is not implemented yet, you cannot log in.
