### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NSTAdventure** [FBlackBox/BlackBox#101]
**Describe the bug** / **描述一下这个错误**
shizuku services is cannot started using ADB shell or ADB over TCP

**To Reproduce** / **复现步骤**
1. Install / Clone Shizuku Manager
2. Start Shizuku services with ADB shell or ADB over TCP
3.  shizuku cannot started
![Screenshot_2022-04-12-14-04-04-77](https://user-images.githubusercontent.com/50813528/162902000-c4c4f950-14e5-480c-9d5e-4e068cad5d53.jpg)

**Expected behavior** / **预期的行为**
清晰而简明地描述你所期望发生的事情。

**Screenshots** / **截图**
如果有，请添加屏幕截图以帮助解释你的问题。

**Mobile Phone Info** / **手机信息**
Xiaomi / Android12

**Logcat** / **日志**
If you are a developer or capable please provide logs for us to analyze.
如果你是开发者或者有能力的请提供日志供我们分析。

**Additional context** / **额外内容**
1. shizuku dev not support any environment than real environment
(Real devices only)

2. click blue text there is doc about shizuku complete with download apk too

3. shizuku can be started on 3 method:
- ADB shell (Shizuku data path) /start.sh
- ADB over TCP just click start with wireless ADB and grant the app to access ADB / USB debugging
- Root simply just click start with root and grant supersu access

i only tried on ADB shell and ADB over TCP both method not working

**APK**
[Documents For shizuku here](https://shizuku.rikka.app/)

**Comment by FBlackBox** [comment]
The application inside Box is not a real application, so it cannot be operated this way at the moment.
