### ISSUE TITLE
> 黑盒1.9测试版刚刚测试了，图片问题已经修复，但是不能创建快捷方式，还有就是现在修复版qq会闪退了，登陆进去以后就会退出来版本经测试，vivo s9安卓11系统，双开微信或者qq以后，已经给了访问存储权限，但是微信或者qq登录上去，想要给好友发送照片，会读取不到相册内容，提示无媒体文件，这个是不是软件没有添加访问文件管理的所有权限导致的，还有一个bug就是给了权限，创建快捷方式到桌面，点击以后也不能创建到桌面，软件挺好用，但是这两个bug导致没法用

### ISSUE THREAD

**Issue by liangxingxingfu510** [FBlackBox/BlackBox#102]
> 黑盒1.9版本经测试，vivo s9安卓11系统，双开微信或者qq以后，已经给了访问存储权限，但是微信或者qq登录上去，想要给好友发送照片，会读取不到相册内容，提示无媒体文件，这个是不是软件没有添加访问文件管理的所有权限导致的，还有一个bug就是给了权限，创建快捷方式到桌面，点击以后也不能创建到桌面，软件挺好用，但是这两个bug导致没法用

已修复图片问题，请下载测试版：https://github.com/AutoBlackBox/BlackBox/releases/tag/Canary-v41

_Originally posted by @FBlackBox in https://github.com/FBlackBox/BlackBox/issues/99#issuecomment-1095945648_

**Comment by liangxingxingfu510** [comment]
测试版刚刚测试了，图片问题已经修复，但是不能创建快捷方式，还有就是现在修复版qq会闪退了，登陆进去以后就会退出来

**Comment by FBlackBox** [comment]
快捷方式有些桌面不支持设置的，创建不了就是不支持。至于你说qq会闪退请给日志吧。
