### ISSUE TITLE
[Feature]虚拟定位功能
目前的虚拟定位功能很不完善，设置了虚拟定位以后无法改为真实位置，请尽快完善这个功能。
另外设定虚拟定位的位置的时候选取界面很不完善，希望后继能够优化。谢谢。

### ISSUE THREAD

**Issue by lordshenone** [FBlackBox/BlackBox#105]
**Is your feature request related to a problem? Please describe.** / **你的功能请求是否与问题有关？请描述。**
A clear and concise description of what the problem is. 
清晰简洁地描述问题是什么。

**Describe the solution you'd like** / **描述你想要的解决方案**
清晰简洁地描述你希望发生什么。

**Additional context** / **额外的内容**
在此添加关于该功能请求的任何其他内容或屏幕截图。

**Comment by FBlackBox** [comment]
Fix https://github.com/FBlackBox/BlackBox/commit/b072636d0b50e1bdcd45ef37b97a0bb77eb57bf5
