### ISSUE TITLE
Game guardian support[Feature]

### ISSUE THREAD

**Issue by deleteBlack666** [FBlackBox/BlackBox#116]
Add game guardian support

**Comment by FBlackBox** [comment]
set targetSdkVersion to 28

**Comment by deleteBlack666** [comment]
> установите targetSdkVersion на 28



> set targetSdkVersion to 28

what exactly to install? can guide

**Comment by deleteBlack666** [comment]
> set targetSdkVersion to 28

oh thanks it helped

**Comment by deleteBlack666** [comment]
> set targetSdkVersion to 28

does not work
