### ISSUE TITLE
分身功能无效[BUG] 

### ISSUE THREAD

**Issue by zorro0799** [FBlackBox/BlackBox#118]
接入google admob广告sdk，aomob初始化后，分身功能失败，如果不初始化分身功能正常

环境
华为p40
 android 11

**Comment by AmySama** [comment]
拿别人开源的二改，植入垃圾广告还敢过来提交问题😅

**Comment by zorro0799** [comment]
admob垃不垃圾我不知道，反正不接海外别的我更不会接，二改不很正常，你敢说你从来没有用过一点别人的代码二改过，道德制高点站的高啊，装什么大尾巴狼

**Comment by AmySama** [comment]
确实没有哟🤣
看见你们这些拿免费开源二改的被骂，就很舒适😋
这么喜欢二改咋不买罗盒的VirtualApp哟😁
跟隔壁某vxp作者一个德性😙
你跟隔壁什么xp的作者可以归类到一起，隔壁某xp作者就不喜欢开源哦☺️

**Comment by zorro0799** [comment]
哎哟，道德标兵又来了，我为什么不买呀，还不是穷嘛，你这么道德这么高要不你买来送人呀，装什么装呀，大家都是俗人，牌坊就别立了，别光看别人，自己脸多长心里要有数

**Comment by AmySama** [comment]
可以评为中国年度爆笑花活之一了🤣
我们可没有想着拿这个公众的东西自己加个广告发布出去😘
用这个技术来赚钱的人才是小人😊
希望以后你出门问路都要赏点小费哦😣

**Comment by zorro0799** [comment]
我这个要脸，我要是看到别人二开，或者抄了人家源码没有开源，我不会说，因为我做不到呀，bat都拿人家东西改改就用，还赚钱，我怎么能骂别人，不能，我没这个脸，在我看来不要说是抄人家的，或二开，你哪怕用过这种抄人家代码写出来的程序都没有资格说别人，谁不知谁呀，低调点，但居然能遇到有人理直气壮的说别人黑，我很白，很佩服，😘😘😘😘😘😘😘😘😘，表情比你打的多吧

**Comment by zorro0799** [comment]
不和你扯了，哥睡觉了，任何回复哥都一笑了而过了，白白😊😊😊😊😊😊😊😊😊😊
