### ISSUE TITLE
如何安装谷歌套件？[Feature]

### ISSUE THREAD

**Issue by yanygm** [FBlackBox/BlackBox#129]
**Is your feature request related to a problem? Please describe.** / **你的功能请求是否与问题有关？请描述。**
A clear and concise description of what the problem is. 
清晰简洁地描述问题是什么。

**Describe the solution you'd like** / **描述你想要的解决方案**
清晰简洁地描述你希望发生什么。

**Additional context** / **额外的内容**
在此添加关于该功能请求的任何其他内容或屏幕截图。

**Comment by FBlackBox** [comment]
设置，GMS管理
