### ISSUE TITLE
[Other]不支持中国联通app，本机有但是软件内没有

### ISSUE THREAD

**Issue by 771695775** [FBlackBox/BlackBox#141]
onedrive也没有

**Comment by 771695775** [comment]
onedrive也没有

**Comment by FBlackBox** [comment]
请下载另一个版本的BlackBox就有了

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

------- Original Message -------
2022年7月5日 星期二 上午 8:34，771695775 ***@***.***> 来信：

**Comment by JackeyAndev** [comment]
请问是哪个版本的BlackBox

**Comment by FBlackBox** [comment]
32没有就装64，64没有就装32

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

------- Original Message -------
2022年7月10日 星期日 下午 2:09，Jackey ***@***.***> 来信：
