### ISSUE TITLE
In android 13 facebook and facebook lite is not working properly

### ISSUE THREAD

**Issue by mubasher380** [FBlackBox/BlackBox#166]
ANR in com.dual.space:p1 (com.dual.space/top.niunaijun.blackbox.proxy.ProxyActivity$P1)
                                                                                                    PID: 8761
                                                                                                    Reason: Input dispatching timed out (fa3c4ff com.facebook.katana/com.facebook.katana.LoginActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false))
                                                                                                    Parent: com.dual.space/top.niunaijun.blackbox.proxy.ProxyActivity$P1
                                                                                                    ErrorId: 90d63c88-d737-441c-beeb-d7288e0ce75f
                                                                                                    Frozen: false
                                                                                                    Load: 2.93 / 2.47 / 2.15

**Comment by NBXXF** [comment]
> ANR in com.dual.space:p1 (com.dual.space/top.niunaijun.blackbox.proxy.ProxyActivity$P1) PID: 8761 Reason: Input dispatching timed out (fa3c4ff com.facebook.katana/com.facebook.katana.LoginActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false)) Parent: com.dual.space/top.niunaijun.blackbox.proxy.ProxyActivity$P1 ErrorId: 90d63c88-d737-441c-beeb-d7288e0ce75f Frozen: false Load: 2.93 / 2.47 / 2.15

hello， Is this solved?
