### ISSUE TITLE
快手弹出“签名验证失败”

### ISSUE THREAD

**Issue by l0neman** [FBlackBox/BlackBox#18]
系统：Android 11
机型：一加 6T（ONEPLUS A6010）

在 BlackBox 64 位版本中安装快手，打开后，会看到快手内部弹出“签名验证失败”的消息，可能由于签名验证失败，导致点击当前用户头像，进入用户发布的视频界面，不能正常加载；点击视频评论按钮，用户评论也无法正常加载。

**Comment by FBlackBox** [comment]
把apk添加到附件。

**Comment by l0neman** [comment]
估计文件太大，附件上传总是失败，先用这个委屈一下
链接：https://pan.baidu.com/s/1SZZDFDX0FT0kPSnq1pxr_Q
提取码：1xt2

**Comment by FBlackBox** [comment]
换个盘吧，百度盘太恶心了
