### ISSUE TITLE
安卓11进入youtube显示没有谷歌服务

### ISSUE THREAD

**Issue by yr54tyty** [FBlackBox/BlackBox#20]
我打开了谷歌服务，安装youtube进入，显示不支持谷歌服务咋回事
![Screenshot_2022-03-05-11-16-47-784_top niunaijun blackboxa64](https://user-images.githubusercontent.com/56281720/156865751-7250d2e5-4ad0-425e-85c7-9ffa59fbfc3f.jpg)
![Uploading Screenshot_2022-03-05-11-16-58-425_top.niunaijun.blackboxa64.jpg…]()

**Comment by FBlackBox** [comment]
手机上是否有Google商店？目前遇到的是其他组件可以装上但是Google商店是32位的，导致没办法装进64位里面，所以没支持到。

**Comment by yr54tyty** [comment]
有谷歌商店，谷歌商店好像是32位的,64位装不进去好像

**Comment by FBlackBox** [comment]
那应该就是这个问题了，64版目前好像没有什么解决办法，只能用32版了。

**Comment by yr54tyty** [comment]
把谷歌商店改64位重新打开谷歌服务开关就好了
