### ISSUE TITLE
小红书无法运行

### ISSUE THREAD

**Issue by Familyye** [FBlackBox/BlackBox#23]
复现：
添加App到BlackBox内到启动页面然后就闪退了
没有输出log日志
App：小红书7.29.0.1  架构：arm64-v8a
安卓11

**Comment by FBlackBox** [comment]
这个为一个开源库的crash，它已经修复了。现在要么小红书更新三方库的版本，要么BlackBox targetSdkVersion降到30以下。

**Comment by FBlackBox** [comment]
这个为一个开源库的crash，它已经修复了（https://github.com/getsentry/sentry-java/issues/904）。现在要么小红书更新三方库的版本，要么BlackBox targetSdkVersion降到30以下。
