### ISSUE TITLE
密码输入框激活时，有的手机会无法唤起输入法，或者唤起了无法点击

### ISSUE THREAD

**Issue by leeManong** [FBlackBox/BlackBox#28]
测试的华为p40 Pro android 10，遇到微信的密码输入框，无法唤起华为手机带的专门针对密码的安全输入法。
vivo 出现能唤起，但无法输入内容。
非密码输入框 是正常的。

**Comment by leeManong** [comment]
测试华为还是没有用，virtualApp这里没有问题。可以正常唤起

**Comment by leeManong** [comment]
qq可以正常唤起，看来是微信的问题。

**Comment by FBlackBox** [comment]
我找到手机后试一下。

**Comment by FBlackBox** [comment]
可以测试一下，https://github.com/AutoBlackBox/BlackBox/releases

**Comment by leeManong** [comment]
你测试的是哪个手机 我用华为p40 pro 微信密码输入 还是没有唤起输入法。

**Comment by FBlackBox** [comment]
唤起了无法点击的那个问题呢

**Comment by leeManong** [comment]
哥们还有个问题 现在的版本打开qq 会闪退  之前我用的那个版本是好的 没有闪退。
无法输入的问题 我找人再测测看。

**Comment by leeManong** [comment]
有个vivo的手机 之前应该是能唤起 无法输入 现在好了，可以输入了。
现在就我这个华为不行。

**Comment by FBlackBox** [comment]
那应该是了，主要是解决那个无法输入的问题，p40目前我还没有设备 找到之后我再看。

**Comment by leeManong** [comment]
qq 我发现是我华为手机打不开  有个小米手机是好的。具体日志在哪看呢。

**Comment by FBlackBox** [comment]
> 手机的Download吗 我没找到，方便留个联系方式吗。好沟通些。

readme上有Telegram群。

**Comment by FBlackBox** [comment]
> qq 我发现是我华为手机打不开 有个小米手机是好的。具体日志在哪看呢。

如果是开发者请查看logcat，如果不是开发者的话Download下面有日志，如果没有可能是手机不允许输出日志了，暂时没办法了。我只有找到手机之后才可以测试。
