### ISSUE TITLE
SafetyNet fails

### ISSUE THREAD

**Issue by jbro129** [FBlackBox/BlackBox#31]
I ran [YASNAC](https://play.google.com/store/apps/details?id=rikka.safetynetchecker&hl=en_US&gl=US) inside BlackBox and it failed both Basic Integrity and CTS. I ran the app after installed GMS for the user.

![image](https://user-images.githubusercontent.com/15088428/157379591-b8acc5c4-99c8-41d8-a963-e728f4a809cd.png)

**Comment by FBlackBox** [comment]
This doesn't seem to matter.
