### ISSUE TITLE
不兼容华为设备

### ISSUE THREAD

**Issue by crazyn2** [FBlackBox/BlackBox#4]
设备: HUAWEI MatePad_Pro Android EMUI 11 Android 10
表现: Chromium内核浏览器闪退
触发条件: 打开应用
目前捕捉不到错误日志，如果计划兼容鸿蒙系统，则需要修复
<img src="https://user-images.githubusercontent.com/45783572/155829403-b6372456-7521-47c8-94b8-15277118b018.gif" width="50%">

**Comment by FBlackBox** [comment]
鸿蒙也是兼容的，chrome在android上也是用Box打开也会crash的 这是个已知问题。
