### ISSUE TITLE
OPPO android 7 安装成功之后，点图标进去闪退

### ISSUE THREAD

**Issue by asdwyujian** [FBlackBox/BlackBox#44]
03-17 20:03:53.493 20658 20658 E AndroidRuntime: FATAL EXCEPTION: main
03-17 20:03:53.493 20658 20658 E AndroidRuntime: Process: net.pandapaint.draw, PID: 20658
03-17 20:03:53.493 20658 20658 E AndroidRuntime: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.Exception: Oops!
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at io.reactivex.OooOo.OooO00o.OooOOOo(RxJavaPlugins.java:4)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at io.reactivex.android.OooO0O0.OooO0O0$OooO0O0.run(HandlerScheduler.java:2)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6190)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
03-17 20:03:53.493 20658 20658 E AndroidRuntime: Caused by: java.lang.Exception: Oops!
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at top.niunaijun.blackbox.utils.Reflector.callByCaller(Reflector.java:201)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.execStartActivity(BaseInstrumentationDelegate.java:348)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4244)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4202)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:3)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4541)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4509)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at net.pandapaint.draw.activities.FlashActivity.o000O0(FlashActivity.java:4)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at net.pandapaint.draw.activities.FlashActivity.o0000oOo(FlashActivity.java:1)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at net.pandapaint.draw.activities.FlashActivity$OooO.onComplete(FlashActivity.java:1)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.OooO0oo(ObservableObserveOn.java:14)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.OooOO0(ObservableObserveOn.java:6)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:3)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at io.reactivex.android.OooO0O0.OooO0O0$OooO0O0.run(HandlerScheduler.java:1)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        ... 8 more
03-17 20:03:53.493 20658 20658 E AndroidRuntime: Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {net.pandapaint.draw/net.pandapaint.draw.activities.MainActivity}; have you declared this activity in your AndroidManifest.xml?
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        at top.niunaijun.blackbox.utils.Reflector.callByCaller(Reflector.java:199)
03-17 20:03:53.493 20658 20658 E AndroidRuntime:        ... 22 more
03-17 20:03:53.599  1309  6965 E EGL_adreno: tid 6965: eglSurfaceAttrib(1338): error 0x3009 (EGL_BAD_MATCH)
03-17 20:03:54.022  1109  1109 E EGL_adreno: tid 1109: eglCreateSyncKHR(2089): error 0x3004 (EGL_BAD_ATTRIBUTE)
03-17 20:03:54.139  1109  1109 E EGL_adreno: tid 1109: eglCreateSyncKHR(2089): error 0x3004 (EGL_BAD_ATTRIBUTE)
03-17 20:03:54.244 20239 20290 E EGL_adreno: tid 20290: eglSurfaceAttrib(1338): error 0x3009 (EGL_BAD_MATCH)

**Comment by FBlackBox** [comment]
提供一下apk
