### ISSUE TITLE
xiaomi android 12 断网测试

### ISSUE THREAD

**Issue by asdwyujian** [FBlackBox/BlackBox#46]
https://pastebin.com/EL2CCxJx

03/17 21:06:05: Launching 'app' on Xiaomi M2011K2C.
Install successfully finished in 322 ms.
$ adb shell am start -n "top.niunaijun.blackboxa32/zzz.framework.ZZZ_SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 28673 on device 'xiaomi-m2011k2c-2e1e6632'.
Connected to process 28718 on device 'xiaomi-m2011k2c-2e1e6632'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/ackboxa32:blac: Late-enabling -Xcheck:jni
D/ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
W/re-initialized>: type=1400 audit(0.0:105258): avc: granted { execute } for path="/data/data/top.niunaijun.blackboxa32/code_cache/startup_agents/fafda4ce-agent-alt.so" dev="dm-11" ino=1139591 scontext=u:r:untrusted_app:s0:c101,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c101,c258,c512,c768 tclass=file app=top.niunaijun.blackboxa32
V/studio.deploy: Startup agent attached to VM
V/studio.deploy: No existing instrumentation found. Loading instrumentation from instruments-2ca9b3e0.jar
W/ackboxa32:blac: DexFile /data/data/top.niunaijun.blackboxa32/code_cache/.studio/instruments-2ca9b3e0.jar is in boot class path but is not in a known location
V/studio.deploy: Applying transforms with cached classes
W/ackboxa32:blac: Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
W/ackboxa32:blac: Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10613; state: DISABLED
V/GraphicsEnvironment: ANGLE Developer option for 'top.niunaijun.blackboxa32' set to: 'default'
V/GraphicsEnvironment: Updatable production driver is not supported on the device.
I/ForceDarkHelperStubImpl: initialize for top.niunaijun.blackboxa32 , ForceDarkOrigin
D/OpenGLRenderer: JNI_OnLoad success
I/MiuiForceDarkConfig: setConfig density:3.500000, mainRule:0, secondaryRule:0, tertiaryRule:0
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
W/ackboxa32:blac: Accessing hidden method Ldalvik/system/VMRuntime;->getRuntime()Ldalvik/system/VMRuntime; (unsupported,core-platform-api, reflection, allowed)
W/ackboxa32:blac: Accessing hidden method Ldalvik/system/VMRuntime;->setHiddenApiExemptions([Ljava/lang/String;)V (blocked,core-platform-api, reflection, denied)
W/BootstrapClass: reflect bootstrap failed:
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.reflection.BootstrapClass.<clinit>(BootstrapClass.java:29)
        at me.weishu.reflection.BootstrapClass.exemptAll(BootstrapClass.java:72)
        at me.weishu.reflection.Reflection.unseal(Reflection.java:34)
        at top.niunaijun.blackbox.BlackBoxCore.doAttachBaseContext(BlackBoxCore.java:128)
        at top.niunaijun.blackboxa.view.main.BlackBoxLoader.attachBaseContext(BlackBoxLoader.kt:87)
        at top.niunaijun.blackboxa.app.AppManager.doAttachBaseContext(AppManager.kt:25)
        at top.niunaijun.blackboxa.app.App.attachBaseContext(App.kt:30)
        at android.app.Application.attach(Application.java:333)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6893)
        at android.app.ActivityThread.access$1600(ActivityThread.java:264)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8085)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     Caused by: java.lang.NoSuchMethodException: dalvik.system.VMRuntime.setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getDeclaredMethod(Class.java:2081)
        at java.lang.reflect.Method.invoke(Native Method) 
        at me.weishu.reflection.BootstrapClass.<clinit>(BootstrapClass.java:29) 
        at me.weishu.reflection.BootstrapClass.exemptAll(BootstrapClass.java:72) 
        at me.weishu.reflection.Reflection.unseal(Reflection.java:34) 
        at top.niunaijun.blackbox.BlackBoxCore.doAttachBaseContext(BlackBoxCore.java:128) 
        at top.niunaijun.blackboxa.view.main.BlackBoxLoader.attachBaseContext(BlackBoxLoader.kt:87) 
        at top.niunaijun.blackboxa.app.AppManager.doAttachBaseContext(AppManager.kt:25) 
        at top.niunaijun.blackboxa.app.App.attachBaseContext(App.kt:30) 
        at android.app.Application.attach(Application.java:333) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1178) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1369) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6893) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:264) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8085) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
W/ackboxa32:blac: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
W/ackboxa32:blac: DexFile /data/user/0/top.niunaijun.blackboxa32/code_cache/1647522365818.dex is in boot class path but is not in a known location
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IContextHubServiceProxy@751ed2b
D/HookManager: hook error: top.niunaijun.blackbox.fake.service.IContextHubServiceProxy@751ed2b
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IActivityTaskManagerProxy@c1b6b46
D/HookManager: hook: top.niunaijun.blackbox.fake.service.libcore.OsStub@83b20b8
D/HookManager: hook: top.niunaijun.blackbox.fake.service.context.ContentServiceStub@eb169f7
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IDisplayManagerProxy@5154ed0
D/HookManager: hook: top.niunaijun.blackbox.fake.service.INotificationManagerProxy@e1427e8
D/HookManager: hook: top.niunaijun.blackbox.fake.service.ILauncherAppsProxy@4dabee7
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IStorageStatsManagerProxy@7c20c00
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPowerManagerProxy@64772f5
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IDevicePolicyManagerProxy@81ae356
D/HookManager: hook: top.niunaijun.blackbox.fake.service.HCallbackProxy@718f273
D/HookManager: hook: top.niunaijun.blackbox.fake.service.ITelephonyRegistryProxy@b94683a
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IActivityClientProxy@7d1bcc7
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IUserManagerProxy@266ec8c
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IVpnManagerProxy@ac45451
D/HookManager: hook: top.niunaijun.blackbox.fake.delegate.AppInstrumentation@81a7642
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IConnectivityManagerProxy@c58a653
D/HookManager: hook: top.niunaijun.blackbox.fake.service.ILocationManagerProxy@8c490bc
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPersistentDataBlockServiceProxy@771f3c1
D/HookManager: hook error: top.niunaijun.blackbox.fake.service.IPersistentDataBlockServiceProxy@771f3c1
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IJobServiceProxy@ed43b54
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAppWidgetManagerProxy@2c059f9
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IVibratorServiceProxy@7670f4a
W/System.err: java.lang.ClassNotFoundException: android.os.IVibratorService$Stub
W/System.err:     at java.lang.Class.classForName(Native Method)
W/System.err:     at java.lang.Class.forName(Class.java:454)
W/System.err:     at java.lang.Class.forName(Class.java:379)
W/System.err:     at top.niunaijun.blackreflection.BlackReflection.getClassNameByBlackClass(BlackReflection.java:246)
W/System.err:     at top.niunaijun.blackreflection.BlackReflection.create(BlackReflection.java:53)
W/System.err:     at black.com.android.internal.os.BRIVibratorServiceStub.get(BRIVibratorServiceStub.java:13)
W/System.err:     at top.niunaijun.blackbox.fake.service.IVibratorServiceProxy.getWho(IVibratorServiceProxy.java:23)
W/System.err:     at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.injectHook(ClassInvocationStub.java:51)
W/System.err:     at top.niunaijun.blackbox.fake.hook.HookManager.injectAll(HookManager.java:182)
W/System.err:     at top.niunaijun.blackbox.fake.hook.HookManager.init(HookManager.java:153)
W/System.err:     at top.niunaijun.blackbox.BlackBoxCore.doAttachBaseContext(BlackBoxCore.java:162)
W/System.err:     at top.niunaijun.blackboxa.view.main.BlackBoxLoader.attachBaseContext(BlackBoxLoader.kt:87)
W/System.err:     at top.niunaijun.blackboxa.app.AppManager.doAttachBaseContext(AppManager.kt:25)
W/System.err:     at top.niunaijun.blackboxa.app.App.attachBaseContext(App.kt:30)
W/System.err:     at android.app.Application.attach(Application.java:333)
W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6893)
W/System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:264)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:210)
W/System.err:     at android.os.Looper.loop(Looper.java:299)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8085)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.IVibratorService$Stub" on path: DexPathList[[zip file "/data/app/~~zMjofRUuFe_emLxThKnuUA==/top.niunaijun.blackboxa32-85-spKugEqFmdC3Qy9QKQg==/base.apk"],nativeLibraryDirectories=[/data/app/~~zMjofRUuFe_emLxThKnuUA==/top.niunaijun.blackboxa32-85-spKugEqFmdC3Qy9QKQg==/lib/arm, /data/app/~~zMjofRUuFe_emLxThKnuUA==/top.niunaijun.blackboxa32-85-spKugEqFmdC3Qy9QKQg==/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err: 	... 27 more
D/HookManager: hook error: top.niunaijun.blackbox.fake.service.IVibratorServiceProxy@7670f4a
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAlarmManagerProxy@c8ed616
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IWindowManagerProxy@dbfca33
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPackageManagerProxy@f89defa
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IMediaSessionManagerProxy@6d7f3b4
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IActivityManagerProxy@bde48d9
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IGraphicsStatsProxy@d91b69b
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IStorageManagerProxy@539b1e4
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAccessibilityManagerProxy@2d61a49
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAccountManagerProxy@b7e9168
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPermissionManagerProxy@e207cbd
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAppOpsManagerProxy@5a77fe
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IDeviceIdentifiersPolicyProxy@f9388d6
D/HookManager: hook: top.niunaijun.blackbox.fake.service.INetworkManagementServiceProxy@2e461f3
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IMediaRouterServiceProxy@47545dc
D/HookManager: hook: top.niunaijun.blackbox.fake.service.ITelephonyManagerProxy@c9e1c61
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAutofillManagerProxy@b53a212
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IShortcutManagerProxy@97f453f
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IWifiManagerProxy@e16cef8
D/HookManager: hook: top.niunaijun.blackbox.fake.service.context.RestrictionsManagerStub@547a80d
D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPhoneSubInfoProxy@62e4a0e
D/Settings: loaded Package: com.huawei.hwid
D/Settings: loaded Package: net.pandapaint.draw
D/BroadcastManager: register: com.huawei.hwid, size: 10
D/BroadcastManager: register: net.pandapaint.draw, size: 6
W/System: A resource failed to call close.

**Comment by FBlackBox** [comment]
请在APP内点击图标启动内部应用，不是用adb启动内部应用。
