### ISSUE TITLE
[BUG] 套娃导致系统瞬间黑屏并强制重启

### ISSUE THREAD

**Issue by mikofe** [FBlackBox/BlackBox#61]
1.在黑盒里面安装黑盒
2.打开黑盒
3.打开黑盒后再次打开黑盒
4.系统会在一瞬间黑屏并强制重启

黑盒1.8.0
Redmi note 8 pro
Miui 12.5.4
Android 11

**Comment by FBlackBox** [comment]
确有此事，可能是miui的bug，其他的手机没事。

**Comment by Saint-Theana** [comment]
在安卓10 RR上同样，不过是软重启。
