### ISSUE TITLE
QQ登录异常显示appid is invalid

### ISSUE THREAD

**Issue by Familyye** [FBlackBox/BlackBox#62]
**异常应用：QQ8.8.83 架构64位** 
**黑盒版本：1.8.0 架构：64位** 
**复现：QQ登录时报错appid is invalid 
一直卡住进不去 使用1.2.0版本黑盒的就可以正常进入**
**设备：红米K20Pro**  
**系统版本：安卓11（R）** 
**MIUI 12.5.6.0**

**Comment by FBlackBox** [comment]
你是从系统克隆还是手动选择安装？我这测试的没问题。你下载个debug包试一下吧。https://github.com/AutoBlackBox/BlackBox/tags

**Comment by Familyye** [comment]
**是手动外部安装的,用1.2.0版本的也是从外部手动安装但是可以运行 1.8.0就不行 debug版也不行 我再试试克隆行不行**

**Comment by FBlackBox** [comment]
克隆应该没问题吧

**Comment by FBlackBox** [comment]
我测试了一下新版，克隆跟手动安装都不会出现appid is invalid问题，是不是你的qq包本身就改过了 触发他原来的校验了
