### ISSUE TITLE
[BUG]  indexing is not possible

### ISSUE THREAD

**Issue by NSTAdventure** [FBlackBox/BlackBox#95]
**Describe the bug** / **描述一下这个错误**
foss store
(fork version of f droid client)
can't indexing repository 

**To Reproduce** / **复现步骤**
1. clone app / apk file of foss store on blackbox
2. open the foss store and try to sync repo
3. foss store will tell you that foss store cannot indexing repository
(via notification)

**Expected behavior** / **预期的行为**
it's should able to indexing repository

**Screenshots** / **截图**

**Mobile Phone Info** / **手机信息**
Realme 5i 
Android 10 Realme UI 1.0

**Logcat** / **日志**
how i can get log without pc?
adb over tcp enabled

**Additional context** / **额外内容**
i use [foss store version 0.1](https://github.com/MyOS-Android/my.android.fossstore) 

[direct link download for foss store version 0.1](https://github.com/MyOS-Android/my.android.fossstore/releases/tag/0.1) 

**APK**

**Comment by FBlackBox** [comment]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/100009830/162538026-ed8b082b-7e67-4fe8-95f1-679657ff9f31.png">

It looks like there is no problem.

**Comment by NSTAdventure** [comment]
> <img alt="image" width="440" src="https://user-images.githubusercontent.com/100009830/162538026-ed8b082b-7e67-4fe8-95f1-679657ff9f31.png">
> 
> It looks like there is no problem.

update:
sometime it work but sometime again not
idk what's wrong with blackbox 🗿🤦

**Comment by FBlackBox** [comment]
Is it possible that the network is the cause?

**Comment by NSTAdventure** [comment]
> Is it possible that the network is the cause?

maybe but ig in my case nope
because my internet currently work fine and i didn't use any dns or vpn for execution
