### ISSUE TITLE
[Other] improvement of xposed

### ISSUE THREAD

**Issue by NSTAdventure** [FBlackBox/BlackBox#96]
problem:
1. there is no xpose manager app so it's make everything difficult like manage xposed module
(manage = install, uninstall, keep track on update of xposed module)

solution:
my idea is what if blackbox developer add xposed manager app and let blackbox user manage xposed from xposed module app?

**Comment by NSTAdventure** [comment]
disclaimer:
actually this is should put on discuss tab but it's looks like developer didn't enable discuss tab on github 🗿🤦

**Comment by FBlackBox** [comment]
The xposed module management interface is available, it is in the settings, under the "xposed switch"

**Comment by NSTAdventure** [comment]
> The xposed module management interface is available, it is in the settings, under the "xposed switch"

but not effective

1. you need manually download and track for update from blackbox

my idea is please make it more simple
just improve the xposed manager

**Comment by suxlil** [comment]
@NSTAdventure 嗯好

**Comment by FBlackBox** [comment]
Box automatically syncs external applications where updates have occurred, eliminating the need for you to manually track versions.

**Comment by NSTAdventure** [comment]
> @NSTAdventure 嗯好

english pls?
i am not understand the chinese language
🙏😅

**Comment by NSTAdventure** [comment]
> Box automatically syncs external applications where updates have occurred, eliminating the need for you to manually track versions.

ok but i hope you make blackbox xposed manager is similar to original xposed manager

manage all your xposed directly from the app instead of manually

**Comment by FBlackBox** [comment]
I don't quite understand what you mean by manually.

**Comment by NSTAdventure** [comment]
> I don't quite understand what you mean by manually.

basically i want you to add xposed manager built in so user can manage xposed directly from the blackbox app
