### ISSUE TITLE
[BUG] 无法创造快捷方式

### ISSUE THREAD

**Issue by woshigenm** [FBlackBox/BlackBox#98]
**Describe the bug** / **描述一下这个错误**
创造快捷方式在桌面上，点击无反应，桌面上也无快捷方式

**To Reproduce** / **复现步骤**
创造快捷权限给予，无法创造快捷方式

**Mobile Phone Info** / **手机信息**
vivo / Android11

**Comment by FBlackBox** [comment]
试一下这个？https://jingyan.baidu.com/article/a378c96077c975f2282830c5.html

**Comment by FBlackBox** [comment]
有些桌面是不允许创建快捷方式的。
