### ISSUE TITLE
[BUG] alook浏览器

### ISSUE THREAD

**Issue by FBlackBox** [FBlackBox/BlackBox#99]
**Describe the bug** / **描述一下这个错误**
不能启动闪退

**Mobile Phone Info** / **手机信息**
红米k40，安卓12，miui13

**Logcat** / **日志**
[top.niunaijun.blackboxa64_logcat.txt](https://github.com/FBlackBox/BlackBox/files/8460740/top.niunaijun.blackboxa64_logcat.txt)

**Comment by liangxingxingfu510** [comment]
黑盒1.9版本经测试，vivo s9安卓11系统，双开微信或者qq以后，已经给了访问存储权限，但是微信或者qq登录上去，想要给好友发送照片，会读取不到相册内容，提示无媒体文件，这个是不是软件没有添加访问文件管理的所有权限导致的，还有一个bug就是给了权限，创建快捷方式到桌面，点击以后也不能创建到桌面，软件挺好用，但是这两个bug导致没法用

**Comment by FBlackBox** [comment]
> 黑盒1.9版本经测试，vivo s9安卓11系统，双开微信或者qq以后，已经给了访问存储权限，但是微信或者qq登录上去，想要给好友发送照片，会读取不到相册内容，提示无媒体文件，这个是不是软件没有添加访问文件管理的所有权限导致的，还有一个bug就是给了权限，创建快捷方式到桌面，点击以后也不能创建到桌面，软件挺好用，但是这两个bug导致没法用

已修复，请下载测试版：https://github.com/AutoBlackBox/BlackBox/releases/tag/Canary-v41

**Comment by liangxingxingfu510** [comment]
测试版刚刚测试了，图片问题已经修复，但是不能创建快捷方式，还有就是现在修复版qq会闪退了，登陆进去以后就会退出来
